version: '3.8'

services:
  # Database service
  postgres:
    image: postgres:16-alpine
    container_name: saas-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-saas}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - saas-network
    restart: unless-stopped

  # Backend API service
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: saas-server
    environment:
      # Server Configuration
      - PORT=8080
      - ENV=${ENV:-docker}
      # Database Configuration
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-saas}
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key-change-this-in-production}
      - JWT_EXPIRY=${JWT_EXPIRY:-24h}
      # CORS Configuration
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
      - SAME_ORIGIN=${SAME_ORIGIN:-false}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3000}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      # OAuth Configuration
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL:-http://localhost:3000/callback/google}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URL=${GITHUB_REDIRECT_URL:-http://localhost:3000/callback/github}
      # LemonSqueezy Configuration
      - LEMON_SQUEEZY_API_KEY=${LEMON_SQUEEZY_API_KEY}
      - LEMON_SQUEEZY_STORE_ID=${LEMON_SQUEEZY_STORE_ID}
      - LEMONS_SQUEEZY_PRODUCT_ID=${LEMONS_SQUEEZY_PRODUCT_ID}
      - LEMON_SQUEEZY_SIGNING_SECRET=${LEMON_SQUEEZY_SIGNING_SECRET}
      # Plunk Configuration
      - PLUNK_SECRET_API_KEY=${PLUNK_SECRET_API_KEY}
      # Admin Configuration
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123_change_in_production}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET:-admin-jwt-secret-key-change-this-in-production}
      - ADMIN_CLIENT_URL=${ADMIN_CLIENT_URL:-http://localhost:3001}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - saas-network
    restart: unless-stopped

  # Client frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        # API Configuration
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}
        # Google OAuth
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        - NEXT_PUBLIC_GOOGLE_REDIRECT_URI=${NEXT_PUBLIC_GOOGLE_REDIRECT_URI:-http://localhost:3000/callback/google}
        # Github OAuth
        - NEXT_PUBLIC_GITHUB_CLIENT_ID=${NEXT_PUBLIC_GITHUB_CLIENT_ID}
        - NEXT_PUBLIC_GITHUB_REDIRECT_URI=${NEXT_PUBLIC_GITHUB_REDIRECT_URI:-http://localhost:3000/callback/github}
        # LemonSqueezy Configuration
        - NEXT_PUBLIC_LEMONSQUEEZY_API_KEY=${NEXT_PUBLIC_LEMONSQUEEZY_API_KEY}
        - NEXT_PUBLIC_LEMONSQUEEZY_STORE_ID=${NEXT_PUBLIC_LEMONSQUEEZY_STORE_ID}
        - NEXT_PUBLIC_LEMON_SQUEEZY_PRODUCT_ID=${NEXT_PUBLIC_LEMON_SQUEEZY_PRODUCT_ID}
        - NEXT_PUBLIC_LEMON_SQUEEZY_VARIANT_ID_1=${NEXT_PUBLIC_LEMON_SQUEEZY_VARIANT_ID_1}
        - NEXT_PUBLIC_LEMON_SQUEEZY_VARIANT_ID_2=${NEXT_PUBLIC_LEMON_SQUEEZY_VARIANT_ID_2}
        - NEXT_PUBLIC_LEMON_SQUEEZY_VARIANT_ID_3=${NEXT_PUBLIC_LEMON_SQUEEZY_VARIANT_ID_3}
    container_name: saas-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - saas-network
    restart: unless-stopped

  # Admin client service
  admin-client:
    build:
      context: ./admin-client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}
    container_name: saas-admin-client
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}
    ports:
      - "3001:3001"
    depends_on:
      - server
    networks:
      - saas-network
    restart: unless-stopped

# Persistent volumes
volumes:
  postgres_data:
    name: saas-postgres-data

# Network configuration
networks:
  saas-network:
    name: saas-network
    driver: bridge 